# Generated by Django 4.2.5 on 2025-04-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LITERATURE', '소설/시/희곡'), ('ECONOMY', '경제/경영'), ('DEVELOPMENT', '자기계발'), ('HUMANITY', '인문/교양'), ('SCIENCE', '과학'), ('HOBBY', '취미/실용'), ('MINORS', '어린이/청소년')], help_text='도서 종류를 선택해주세요.', max_length=100, unique=True, verbose_name='종류')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('LITERATURE', '소설/시/희곡'), ('ECONOMY', '경제/경영'), ('DEVELOPMENT', '자기계발'), ('HUMANITY', '인문/교양'), ('SCIENCE', '과학'), ('HOBBY', '취미/실용'), ('MINORS', '어린이/청소년')], default=1, help_text='도서 종류를 선택해주세요.', max_length=100, unique=True, verbose_name='종류'),
            preserve_default=False,
        ),
    ]
